######################################################################
#Python Script Generated by GeneratePythonScript Algorithm
######################################################################
LoadISISNexus(Filename=r'/home/tianhl/workarea/CSNS_REFL_SIM/app/test/test.nxs',OutputWorkspace='test')

